### ISSUE TITLE
unreachable deadline

### ISSUE THREAD

**Issue by nonseodion** [DePayFi/depay-ethereum-payment-processing#2]
The swap deadline returned by `swapDeadline` is unreachable considering  the way Uniswap checks deadline using a modifier attached to the swap functions
```
modifier ensure(uint deadline) {
        require(deadline >= block.timestamp, 'UniswapV2Router: EXPIRED');
        _;
    }
```
`swapDeadline` returns `block.timestamp` of the same block with 60 minutes added which will always makes the deadline 60 minutes out. I think supplying it from the frontend might be a good fix.

**Comment by spape** [comment]
We just released version 1 of our payment processor contract. Your comment is based on our beta version, which we just replaced.  
  
You're addressing a valid point here, which has been addressed by us and is implemented now through and through:

[Here](https://github.com/DePayFi/depay-ethereum-payment-processing/blob/master/contracts/DePayPaymentProcessorV1.sol#L40)

[Here](https://github.com/DePayFi/depay-ethereum-payment-processing/blob/master/contracts/DePayPaymentProcessorV1.sol#L45)

[Here](https://github.com/DePayFi/depay-ethereum-payment-processing/blob/master/contracts/DePayPaymentProcessorV1Uniswap01.sol#L31)

[and Here](https://github.com/DePayFi/depay-ethereum-payment-processing/blob/master/contracts/DePayPaymentProcessorV1Uniswap01.sol#L51-L72)

We are launching our Gitcoin audit program Today. Keep an eye open on Gitcoin if you want to submit a structured, complete audit for V1.

**Comment by nonseodion** [comment]
Alright thanks. I'll do that.
